name: Dotfile Setup CI

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-test:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Initialize chezmoi
        run: |
          mkdir -p ~/.config/chezmoi
          echo -e "[data]\n    email = \"github-actions[bot]@users.noreply.github.com\"\n    espanso = false" > ~/.config/chezmoi/chezmoi.toml
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/ageha734/dotfile.git

      - name: Install proto
        run: bash <(curl -fsSL https://moonrepo.dev/install/proto.sh)

      - name: Update README with latest successful run date
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          current_date=$(date -u +'%Y年%m月%d日')
          sed -i'.bak' "//a ✅ **${current_date}** に動作確認済み" README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: 最終動作確認日を更新" || echo "No changes to commit"
          git push
